### ISSUE TITLE
Update metadata.json to GNOME version 46

### ISSUE THREAD

**Issue by Lashriel** [neuromorph/touchx#2]
See title.

Currently, as distributed, the extension only supports GNOME Shell versions up to 45. The only thing needed to "update" to GNOME Shell version 46, as I've tested, is changing the shell version in metadata.json.

**Comment by neuromorph** [comment]
Yes, I've been meaning to port it to Gnome 46 and did not really expect much to change. However, I could not yet do the tests to confirm.
Thank you for reporting that the extension works fine in 46. I will update and upload the new version soon.
Meanwhile if you face any issues, feel free to raise here.

Thanks!

**Comment by mBilG** [comment]
That does not work in Gnome 45 and 46 (at least not on Fedora 40 with Gnome 46).

There are changes to gjs that require code changes:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

I've updated the imports, but I guess there are more updates required. Will test when I have some time.

**Comment by neuromorph** [comment]
It is finally ported to Gnome 46 along with multi-touch support and is live in Gnome extensions site.

Closing the issue, Thank you for your feedback.
